"""empty message

Revision ID: b558e7f892bc
Revises: 
Create Date: 2024-05-20 10:58:48.177433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b558e7f892bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('national_Id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('business_type', sa.String(length=120), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('rendered_data', sa.Text(), nullable=False),
    sa.Column('licence_number', sa.String(length=20), nullable=False),
    sa.Column('licence_image', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('licence_number'),
    sa.UniqueConstraint('national_Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
